// Year placement and combat stats are fictional pacing, not an official curriculum.
export const TEXTBOOKS = [
  {
    id: 'textbook-math',
    major: 'math',
    short: '高等数学',
    year: 1,
    hp: 30,
    damage: 6,
    speed: 1,
    size: 1,
    color: '#ffda75',
    file: 'textbook-math.jpg',
    crop: 0,
  },
  {
    id: 'textbook-linear',
    major: 'math',
    short: '线性代数',
    year: 1,
    hp: 48,
    damage: 6,
    speed: 0.78,
    size: 1.2,
    color: '#ffc35d',
    file: 'textbook-linear.jpg',
    crop: 0,
  },
  {
    id: 'textbook-probability',
    major: 'math',
    short: '概率统计',
    year: 2,
    hp: 57,
    damage: 11,
    speed: 1.3,
    size: 0.95,
    color: '#b9ef86',
    file: 'textbook-probability.jpg',
    crop: 0,
  },
  {
    id: 'textbook-ode',
    major: 'math',
    short: '常微分方程',
    year: 2,
    hp: 73,
    damage: 11,
    speed: 0.85,
    size: 1.1,
    color: '#e3c573',
    file: 'textbook-ode.jpg',
    crop: 0,
  },
  {
    id: 'textbook-complex',
    major: 'math',
    short: '复变函数',
    year: 3,
    hp: 96,
    damage: 16,
    speed: 1.22,
    size: 1.08,
    color: '#f2a7ef',
    file: 'textbook-complex.jpg',
    crop: 0,
  },
  {
    id: 'textbook-real',
    major: 'math',
    short: '实变函数',
    year: 3,
    hp: 117,
    damage: 17,
    speed: 0.8,
    size: 1.25,
    color: '#d7b9ff',
    file: 'textbook-real.jpg',
    crop: 0,
  },
  {
    id: 'textbook-numerical',
    major: 'math',
    short: '数值分析',
    year: 4,
    hp: 145,
    damage: 21,
    speed: 1.12,
    size: 1.18,
    color: '#ff956f',
    file: 'textbook-numerical.jpg',
    crop: 0,
  },
  {
    id: 'textbook-functional',
    major: 'math',
    short: '应用数学方法',
    year: 4,
    hp: 174,
    damage: 22,
    speed: 0.73,
    size: 1.4,
    color: '#ff739c',
    file: 'textbook-functional.jpg',
    crop: 0,
  },
  {
    id: 'textbook-c',
    major: 'cs',
    short: 'C程序设计',
    year: 1,
    hp: 28,
    damage: 6,
    speed: 1.1,
    size: 1,
    color: '#96edaa',
    file: 'textbook-c.jpg',
    crop: 0,
  },
  {
    id: 'textbook-discrete',
    major: 'cs',
    short: '离散数学',
    year: 1,
    hp: 44,
    damage: 6,
    speed: 0.83,
    size: 1.12,
    color: '#71dac2',
    file: 'textbook-discrete.jpg',
    crop: 0,
  },
  {
    id: 'textbook-cs',
    major: 'cs',
    short: '数据结构',
    year: 2,
    hp: 60,
    damage: 11,
    speed: 0.96,
    size: 1.06,
    color: '#74efd0',
    file: 'textbook-cs.jpg',
    crop: 0.52,
  },
  {
    id: 'textbook-computer',
    major: 'cs',
    short: '计算机组成',
    year: 2,
    hp: 79,
    damage: 12,
    speed: 0.76,
    size: 1.25,
    color: '#a8adff',
    file: 'textbook-computer.jpg',
    crop: 0,
  },
  {
    id: 'textbook-network',
    major: 'cs',
    short: '计算机网络',
    year: 3,
    hp: 92,
    damage: 16,
    speed: 1.3,
    size: 0.95,
    color: '#7cdfff',
    file: 'textbook-network.jpg',
    crop: 0,
  },
  {
    id: 'textbook-os',
    major: 'cs',
    short: '操作系统',
    year: 3,
    hp: 124,
    damage: 17,
    speed: 0.65,
    size: 1.35,
    color: '#b7a2ff',
    file: 'textbook-os.jpg',
    crop: 0,
  },
  {
    id: 'textbook-compiler',
    major: 'cs',
    short: '编译原理',
    year: 4,
    hp: 152,
    damage: 22,
    speed: 0.87,
    size: 1.3,
    color: '#ffaf69',
    file: 'textbook-compiler.jpg',
    crop: 0,
  },
  {
    id: 'textbook-ml',
    major: 'cs',
    short: '机器学习',
    year: 4,
    hp: 167,
    damage: 21,
    speed: 1.17,
    size: 1.18,
    color: '#ff7998',
    file: 'textbook-ml.jpg',
    crop: 0,
  },
  {
    id: 'textbook-cad',
    major: 'arch',
    short: '建筑制图',
    year: 1,
    hp: 26,
    damage: 6,
    speed: 1.2,
    size: 1,
    color: '#ffae79',
    file: 'textbook-cad.jpg',
    crop: 0,
  },
  {
    id: 'textbook-design',
    major: 'arch',
    short: '建筑设计初步',
    year: 1,
    hp: 41,
    damage: 6,
    speed: 0.92,
    size: 1.08,
    color: '#ffc68a',
    file: 'textbook-design.jpg',
    crop: 0,
  },
  {
    id: 'textbook-history',
    major: 'arch',
    short: '建筑史',
    year: 2,
    hp: 66,
    damage: 11,
    speed: 0.84,
    size: 1.15,
    color: '#e6b8ed',
    file: 'textbook-history.jpg',
    crop: 0,
  },
  {
    id: 'textbook-arch',
    major: 'arch',
    short: '建筑构造',
    year: 2,
    hp: 83,
    damage: 12,
    speed: 0.7,
    size: 1.3,
    color: '#8fb9ff',
    file: 'textbook-arch.jpg',
    crop: 0,
  },
  {
    id: 'textbook-thermal',
    major: 'arch',
    short: '建筑热环境',
    year: 3,
    hp: 101,
    damage: 16,
    speed: 1.16,
    size: 1.1,
    color: '#ffa15f',
    file: 'textbook-thermal.jpg',
    crop: 0,
  },
  {
    id: 'textbook-structure',
    major: 'arch',
    short: '建筑结构',
    year: 3,
    hp: 129,
    damage: 17,
    speed: 0.7,
    size: 1.36,
    color: '#a6beff',
    file: 'textbook-structure.jpg',
    crop: 0,
  },
  {
    id: 'textbook-urban',
    major: 'arch',
    short: '城市设计',
    year: 4,
    hp: 149,
    damage: 21,
    speed: 1.05,
    size: 1.2,
    color: '#acdf98',
    file: 'textbook-urban.jpg',
    crop: 0,
  },
  {
    id: 'textbook-green',
    major: 'arch',
    short: '绿色建筑',
    year: 4,
    hp: 180,
    damage: 22,
    speed: 0.8,
    size: 1.4,
    color: '#80e8a7',
    file: 'textbook-green.jpg',
    crop: 0,
  },
] as const;
export type TextbookId = (typeof TEXTBOOKS)[number]['id'];
export const textbook = (id: TextbookId) => TEXTBOOKS.find((b) => b.id === id)!;
export const YEAR_NAMES = ['', '大一', '大二', '大三', '大四'] as const;
